name = "smarttext-ssr"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = "dist/smarttext-ssr/browser"
main = "dist/smarttext-ssr/server/server.mjs"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.mjs"]

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.json"]

[[build.upload.rules]]
type = "Data"
globs = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.ico", "**/*.webp"]

# Environment variables
[vars]
NODE_ENV = "production"

# Routes configuration
[[routes]]
pattern = "smarttext-ssr.pages.dev/*"
zone_name = "smarttext-ssr.pages.dev"

# Cache configuration
[cache]
browser_ttl = 31536000
edge_ttl = 31536000

# Security headers
[security]
hsts = true
hsts_include_subdomains = true
hsts_max_age = 31536000

# Performance optimizations
[performance]
minify = true
brotli = true
